version: 2
dependencies:
    override:
        - pip install awscli
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - run:
          name: install dependencies
          command: sudo pip install awscli

=======
>>>>>>> parent of 5d25d4c... Yet another circle test
=======
>>>>>>> parent of 5d25d4c... Yet another circle test
=======
>>>>>>> parent of 5d25d4c... Yet another circle test
  deploy:
    docker:
      - image: circleci/python:3.6
    working_directory: /Users/trevor/Documents/GitHub/trevoryoung.co
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync /Users/trevor/Documents/GitHub/trevoryoung.co s3://trevoryoung.design --delete
