version: 2
dependencies:
    override:
        - pip install awscli
jobs:
  build:
    working_directory: /Users/trevor/Documents/GitHub/trevoryoung.co
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: install dependencies
          command:
                sudo pip install awscli

  deploy:
    docker:
      - image: circleci/python:[latest]
    working_directory: /Users/trevor/Documents/GitHub/trevoryoung.co
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync /Users/trevor/Documents/GitHub/trevoryoung.co s3://trevoryoung.design --delete


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
