version: 2
dependencies:
    override:
        - pip install awscli
jobs:
  build:
    docker:
      - image: circleci/node:7.10.0
    working_directory: ~/trevoryoung.co
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: install dependencies
          command: |
            sudo apt install python-pip python-dev
            sudop pip install awscli

  deploy:
    docker:
      - image: circleci/node:7.10.0
    working_directory: ~/trevoryoung.co
    steps:
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync /Users/trevor/Documents/GitHub/trevoryoung.co s3://trevoryoung.design --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
